export default class CommonConstants {

  static readonly PREFERENCE_INSTANCE_NAME: string = 'myStore';

  static readonly PREFERENCE_NOTE_KEY: string = 'noteIdArr';

  static readonly ADD_NOTE: string = 'add';

  static readonly MODIFY_NOTE: string = 'modify';

  static readonly SAVE_DIALOG: string = 'save';

  static readonly DELETE_DIALOG: string = 'delete';

  static readonly START_HOUR_OF_MORNING: number = 0;

  static readonly END_HOUR_OF_MORNING: number = 12;

  static readonly MORNING_OF_DAY: string = 'AM';

  static readonly POST_MERIDIEM: string = 'PM';

  static readonly LOGIN_SIZE: number = 20

  static readonly LOGIN_COLOR: string = '#007AFF'

  static readonly LOGIN: string = '登录'

  static readonly REGISTERACCOUNT : string = '注册账号'

  static readonly REGISTER : string = '注册'

  static readonly FORGET : string = '忘记密码'

  static readonly USERNAME : string = '请输入用户名'

  static readonly PASSWORD : string = '请输入密码'

  static readonly CONFIRMPASSWORD : string = '确认密码'

  static readonly CODE : string = '请输入邀请码'

  static readonly INPUT_ACCOUNT_LENGTH = 11;

  static readonly INPUT_PASSWORD_LENGTH = 8;

  static readonly INPUT_PADDING_LEFT = 0;

  static readonly LOGIN_DELAY_TIME = 2000;

  static readonly COMMON_SPACE = 12;

  static readonly HOME_TITLE = '首页';

  static readonly LOGIN_METHODS_SPACE = 44;

  static readonly FULL_PARENT = '100%';

  static readonly BUTTON_WIDTH = '90%';

  static readonly HOME_TAB_INDEX = 0;

  static readonly MINE_TAB_INDEX = 1;

  static readonly SET_SLIDER_MIN: number = 14;

  static readonly SET_SLIDER_MAX: number = 22;

  static readonly SET_SLIDER_STEP: number = 2;

  static readonly SET_SIZE_SMALL: number = 14;

  static readonly SET_SIZE_NORMAL: number = 16;

  static readonly SET_SIZE_LARGE: number = 18;

  static readonly SET_SIZE_EXTRA_LARGE: number = 20;

  static readonly SET_SIZE_HUGE: number = 24;

}