export default class StyleConstants {

  static readonly FULL_HEIGHT: string = '100%';

  static readonly FULL_WIDTH: string = '100%';

  static readonly CONTENT_WIDTH: string = '87%';

  static readonly TEXT_INPUT_WIDTH: string = '93%';

  static readonly MEMO_LIST_SPACE: string = '12';

  static readonly NOTE_CONTENT_HEIGHT: string = '90%';

  static readonly DIALOG_CONTENT_WIDTH: string = '93%';

  static readonly TITLE_BAR_HEIGHT_PERCENT: string = '7.2%';

  static readonly SLIDER_LAYOUT_LEFT_PERCENT: string = '6.5%';

  static readonly SLIDER_LAYOUT_TOP_PERCENT: string = '3.2%';

  static readonly A_WIDTH_PERCENT: string = '12.5%';

  static readonly SLIDER_WIDTH_PERCENT: string = '75%';

  static readonly SLIDER_HORIZONTAL_MARGIN_PERCENT: string = '3.3%';

  static readonly SLIDER_TOP_MARGIN_PERCENT: string = '1%';

  static readonly SLIDER_BOTTOM_MARGIN_PERCENT: string = '6.2%';

  static readonly SET_CHAT_HEAD_SIZE_PERCENT: string = '8.9%';

  static readonly HEAD_RIGHT_PERCENT: string = '6.7%';

  static readonly HEAD_LEFT_PERCENT: string = '2.2%';

  static readonly HEAD_ASPECT_RATIO: number = 1;

  static readonly CHAT_TOP_MARGIN_PERCENT: string = '3.1%';

  static readonly DOUBLE_ROW_MIN: number = 28;

  static readonly UNIT_FP: string = 'fp';

  static readonly MAX_CHAT_WIDTH_PERCENT: string = '64.4%';

}